In [1]:
import os
import io
import PySimpleGUI as sg
from PIL import Image

font = ("Roboto", 20)
sg.theme('Dark Blue')

cwd = os.path.expanduser('~/Pictures')
file_types = [("JPEG (*.jpg)", "*.jpg"),
              ("All files (*.*)", "*.*")]

allign_center = [  
    [
        sg.Text("Image Sample"),
    ],
    [
        sg.Image(key="-IMAGE_EXAMPLE_1-"),
        sg.Image(key="-IMAGE_EXAMPLE_3-"),
        sg.Image(key="-IMAGE_EXAMPLE_2-")
    ],
    [
        sg.Text("Confident = "),
    ],
    [
        sg.Image(key="-IMAGE_PREDICTION-")
    ],
    [
        sg.Text("Image File Path"),
        sg.Input(size=(25, 1), enable_events=True, key="-FILE_PATH-"),
        sg.FileBrowse(initial_folder=cwd, file_types=file_types),
    ],
    [
        sg.Button("Submit Image", font=("Roboto", 14))
    ],
]

main_menu_window = [
    [sg.Push(), sg.Column(allign_center, element_justification='c')]
]

window = sg.Window("Dog Breed Classification", main_menu_window)
while True:
    event, values = window.read()
    if event in (sg.WIN_CLOSED, "Exit"):
        break
    elif event == 'Submit Image':
        filename = values["-FILE_PATH-"]
        if os.path.exists(filename):
            image = Image.open(values["-FILE_PATH-"])
            image.thumbnail((400, 400))
            bio = io.BytesIO()
            image.save(bio, format="PNG")
            window["-IMAGE_PREDICTION-"].update(data=bio.getvalue())
            window["-IMAGE_EXAMPLE_1-"].update(data=bio.getvalue())
            window["-IMAGE_EXAMPLE_2-"].update(data=bio.getvalue())
            window["-IMAGE_EXAMPLE_3-"].update(data=bio.getvalue())

window.close()

In [13]:
import matplotlib.pyplot as plt
import numpy as np
import PIL
import tensorflow as tf
from imutils import paths

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

# img_height = 120
# img_width = 120
# dog_path = "n02106166_1031.jpg"

# class_names = ['Border_collie', 'German_shepherd', 'golden_retriever', 'papillon', 'toy_poodle']

# interpreter = tf.lite.Interpreter(model_path="model.tflite")
# interpreter.get_signature_list()

# img = tf.keras.utils.load_img(
#     dog_path, target_size=(img_height, img_width)
# )
# img_array = tf.keras.utils.img_to_array(img)
# img_array = tf.expand_dims(img_array, 0) # Create a batch

# classify_lite = interpreter.get_signature_runner('serving_default')
# # classify_lite

# predictions_lite = classify_lite(sequential_input=img_array)['dense_1']
# score_lite = tf.nn.softmax(predictions_lite)

# print(score_lite)

# print(
#     "This image most likely belongs to {} with a {:.2f} percent confidence."
#     .format(class_names[np.argmax(score_lite)], 100 * np.max(score_lite))
# )

def predictDog(dog_path):
    img_height = 120
    img_width = 120

    class_names = ['Border_collie', 'German_shepherd', 'golden_retriever', 'papillon', 'toy_poodle']

    interpreter = tf.lite.Interpreter(model_path="model.tflite")
    interpreter.get_signature_list()

    img = tf.keras.utils.load_img(
        dog_path, target_size=(img_height, img_width)
    )
    img_array = tf.keras.utils.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0) # Create a batch

    classify_lite = interpreter.get_signature_runner('serving_default')
    # classify_lite

    predictions_lite = classify_lite(sequential_input=img_array)['dense_1']
    score_lite = tf.nn.softmax(predictions_lite)

    print(score_lite)

    print(
        "This image most likely belongs to {} with a {:.2f} percent confidence."
        .format(class_names[np.argmax(score_lite)], 100 * np.max(score_lite))
    )

dog_path = "n02106166_1032.jpg"
predictDog(dog_path)


tf.Tensor([[0.7720511  0.03176995 0.0043811  0.18227848 0.00951935]], shape=(1, 5), dtype=float32)
This image most likely belongs to Border_collie with a 77.21 percent confidence.


In [1]:
import os
import io
import PIL
import numpy as np
import tensorflow as tf
import PySimpleGUI as sg
import matplotlib.pyplot as plt

from PIL import Image
from imutils import paths
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

def predictDog(dog_path):
    img_height = 120
    img_width = 120

    class_names = ['Border_collie', 'German_shepherd', 'golden_retriever', 'papillon', 'toy_poodle']

    interpreter = tf.lite.Interpreter(model_path="model_anjing.tflite")
    interpreter.get_signature_list()

    img = tf.keras.utils.load_img(
        dog_path, target_size=(img_height, img_width)
    )
    img_array = tf.keras.utils.img_to_array(img)
    img_array = tf.expand_dims(img_array, 0) # Create a batch

    classify_lite = interpreter.get_signature_runner('serving_default')

    predictions_lite = classify_lite(sequential_2_input=img_array)['outputs']
    score_lite = tf.nn.softmax(predictions_lite)

    print(score_lite)

    print(
        "This image most likely belongs to {} with a {:.2f} percent confidence."
        .format(class_names[np.argmax(score_lite)], 100 * np.max(score_lite))
    )

    dog_breed = class_names[np.argmax(score_lite)]
    confident = 100 * np.max(score_lite)

    return dog_breed, confident

# dog_path = "n02106166_1032.jpg"
# predictDog(dog_path)

font = ("Roboto", 20)
sg.theme('Dark Blue')

cwd = os.path.expanduser('~/Pictures')
file_types = [("JPEG (*.jpg)", "*.jpg"),
              ("All files (*.*)", "*.*")]

allign_center = [  
    # [
    #     sg.Text("Image Sample"),
    # ],
    # [
    #     sg.Image(key="-IMAGE_EXAMPLE_1-"),
    #     sg.Image(key="-IMAGE_EXAMPLE_3-"),
    #     sg.Image(key="-IMAGE_EXAMPLE_2-")
    # ],
    [
        sg.Text("Dog Breed : ", key="-DOG_BREED-"),
    ],
    [
        sg.Text("Confident : ", key="-CONFIDENT-"),
    ],
    [
        sg.Image(key="-IMAGE_PREDICTION-")
    ],
    [
        sg.Text("Image File Path"),
        sg.Input(size=(25, 1), enable_events=True, key="-FILE_PATH-"),
        sg.FileBrowse(initial_folder=cwd, file_types=file_types),
    ],
    [
        sg.Button("Submit Image", font=("Roboto", 14))
    ],
]

main_menu_window = [
    [sg.Push(), sg.Column(allign_center, element_justification='c')]
]

window = sg.Window("Dog Breed Classification", main_menu_window)
while True:
    event, values = window.read()
    if event in (sg.WIN_CLOSED, "Exit"):
        break
    elif event == 'Submit Image':
        filename = values["-FILE_PATH-"]
        print(filename)
        dog_breed, confident = predictDog(filename)
        dog_breed = "Dog Breed : " + dog_breed
        confident = "Confident : " + str(round(confident, 2)) + "%"
        if os.path.exists(filename):
            image = Image.open(values["-FILE_PATH-"])
            image.thumbnail((400, 400))
            bio = io.BytesIO()
            image.save(bio, format="PNG")
            window["-IMAGE_PREDICTION-"].update(data=bio.getvalue())
            window["-DOG_BREED-"].update(dog_breed)
            window["-CONFIDENT-"].update(confident)
            # window["-IMAGE_EXAMPLE_1-"].update(data=bio.getvalue())
            # window["-IMAGE_EXAMPLE_2-"].update(data=bio.getvalue())
            # window["-IMAGE_EXAMPLE_3-"].update(data=bio.getvalue())

window.close()


C:/Users/marvi/Downloads/n02106166_1032.jpg
tf.Tensor([[8.9505887e-01 1.2851220e-07 1.8617488e-11 1.0486461e-01 7.6364027e-05]], shape=(1, 5), dtype=float32)
This image most likely belongs to Border_collie with a 89.51 percent confidence.
C:/Users/marvi/Downloads/n02106166_1031.jpg
tf.Tensor([[1.0000000e+00 3.0044526e-12 3.3357627e-21 6.2398270e-10 5.3999998e-20]], shape=(1, 5), dtype=float32)
This image most likely belongs to Border_collie with a 100.00 percent confidence.
C:/Users/marvi/Downloads/golden.jpeg
tf.Tensor([[2.9935284e-19 1.0071400e-11 1.0000000e+00 5.4040528e-15 2.3301825e-09]], shape=(1, 5), dtype=float32)
This image most likely belongs to golden_retriever with a 100.00 percent confidence.
